training_pipeline_config:
  pipeline_name: energy
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://archive.ics.uci.edu/ml/machine-learning-databases/00242/ENB2012_data.xlsx
  raw_data_dir: raw_data
  ingested_dir: ingested_dat
  ingested_train_dir: train
  ingested_test_dir: test

data_validation_config:
  schema_dir: config
  schema_file_name: schema.json
  report_file_name: report.json
  report_page_file_name: report.html

data_transformatin_config:
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessed_dir: preprocessed
  preprocessed_object_file_name: preprossed.pkl

model_trainer_config:
  trained_model_dir: trained_model
